### PR TITLE
Private transactions NutsComm address needs a second-level domain

### PR DESCRIPTION
**Pull request by gerardsn**
needed for https://github.com/nuts-foundation/nuts-node/pull/1695

### CODE REVIEW

**Comment by reinkrul** [comment]
Why isn't `nodeA` (e.g.) allowed?

**Comment by gerardsn** [comment]
We added some filtering to the auto-discovery of NutsComm endpoints in https://www.github.com/nuts-foundation/nuts-node/pull/1412. (Mainly to prevent discovery and subsequent connection to addresses like localhost.) The lists includes all subdomains of a specific set of TLDs, a few second-level domains, and all TLDs.

This mechanism is now reused to validate if the NutsComm addresses in the DID document is valid. single word domains like `nodeA` are TLDs and prevent a node from starting in strictmode.

**Comment by gerardsn** [comment]
Maybe the no TLD requirement should be dropped? (localhost is already filtered in the reserved set of TLDs)

**Comment by reinkrul** [comment]
Ah, but local/demo/workshop setups probably don't run in strict mode, so that'll keep working?

**Comment by gerardsn** [comment]
Yes, this is only an issue in strict mode. In non-strict mode an error is logged but the node keeps running.

**Review by reinkrul — APPROVED** [review]

**Comment by gerardsn** [comment]
obsoleted by https://github.com/nuts-foundation/nuts-node/pull/1725

**Pull request closed without merging**
